### ISSUE TITLE
Use XDG_CONFIG_HOME for config files

### ISSUE THREAD

**Issue by tiran** [martbab/ipa-docker-test-runner#7]
It's bad style to put config files in $HOME. The correct location for config files is the directory `$XDG_CONFIG_HOME/$APP_NAME/` with `XDG_CONFIG_HOME=os.environ('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))`.

**Comment by martbab** [comment]
Thanks for the suggestion, I have modified the config path construction logic to be more conformant with XDG specification.
